timestamp = 1569759611

[signatures]
ClientMode = 820716208
clientstate_choked_commands = 19752
clientstate_delta_ticks = 372
clientstate_last_outgoing_command = 19748
convar_name_hash_table = 192760
dwClientState = 5836172
dwClientState_GetLocalPlayer = 384
dwClientState_IsHLTV = 19776
dwClientState_Map = 652
dwClientState_MapDirectory = 392
dwClientState_MaxPlayer = 904
dwClientState_PlayerInfo = 21176
dwClientState_State = 264
dwClientState_ViewAngles = 19848
dwDormant = 237
dwEntityList = 80781060
dwForceAttack = 51623408
dwForceAttack2 = 51623420
dwForceBackward = 51623492
dwForceForward = 51623504
dwForceJump = 85644728
dwForceLeft = 51623372
dwForceRight = 51623360
dwGameDir = 6518512
dwGetAllClasses = 13749500
dwGlobalVars = 5835408
dwGlowObjectManager = 86287160
dwInput = 85282640
dwInterfaceLinkList = 9219812
dwLocalPlayer = 13597260
dwMouseEnable = 13620632
dwMouseEnablePtr = 13620584
dwPlayerResource = 51616076
dwRadarBase = 85191780
dwSensitivity = 13620276
dwSensitivityPtr = 13620232
dwSetClanTag = 563728
dwViewMatrix = 80722228
dwWeaponTable = 85285400
dwWeaponTableIndex = 12860
dwYawPtr = 13619704
dwZoomSensitivityRatioPtr = 13640728
dwbSendPackets = 863882
dwppDirect3DDevice9 = 679984
interface_engine_cvar = 256492
m_pStudioHdr = 10572
m_pitchClassPtr = 85192464
m_yawClassPtr = 13619704

[netvars]
m_ArmorValue = 45888
m_Collision = 800
m_CollisionGroup = 1140
m_Local = 12220
m_MoveType = 604
m_OriginalOwnerXuidHigh = 12724
m_OriginalOwnerXuidLow = 12720
m_aimPunchAngle = 12332
m_aimPunchAngleVel = 12344
m_bConnected = 2788
m_bGunGameImmunity = 14636
m_bHasDefuser = 45904
m_bHasHelmet = 45876
m_bInReload = 12933
m_bIsDefusing = 14616
m_bIsScoped = 14608
m_bSpotted = 2365
m_bSpottedByMask = 2432
m_clrRender = 112
m_dwBoneMatrix = 9896
m_fAccuracyPenalty = 13072
m_fFlags = 260
m_flC4Blow = 10640
m_flDefuseCountDown = 10668
m_flDefuseLength = 10664
m_flFallbackWear = 12736
m_flFlashDuration = 41972
m_flFlashMaxAlpha = 41968
m_flNextPrimaryAttack = 12824
m_flTimerLength = 10644
m_hActiveWeapon = 12024
m_hMyWeapons = 11768
m_hMyWearables = 12036
m_hObserverTarget = 13192
m_hOwner = 10700
m_hOwnerEntity = 332
m_hViewModel = 13048
m_iAccountID = 12232
m_iClip1 = 12868
m_iCompetitiveRanking = 6788
m_iCompetitiveWins = 7048
m_iCrosshairId = 45996
m_iEntityQuality = 12204
m_iFOVStart = 12776
m_iGlowIndex = 41996
m_iHealth = 256
m_iItemDefinitionIndex = 12202
m_iItemIDHigh = 12224
m_iKills = 3116
m_iObserverMode = 13172
m_iPing = 2856
m_iShotsFired = 41856
m_iState = 12856
m_iTeamNum = 244
m_iViewModelIndex = 12832
m_iWorldDroppedModelIndex = 12840
m_iWorldModelIndex = 12836
m_lifeState = 607
m_nActiveCoinRank = 19144
m_nFallbackPaintKit = 12728
m_nFallbackSeed = 12732
m_nFallbackStatTrak = 12740
m_nForceBone = 9868
m_nModelIndex = 600
m_nMusicID = 19404
m_nPersonaDataPublicLevel = 19664
m_nSequence = 10428
m_nTickBase = 13356
m_rgflCoordinateFrame = 1092
m_szCustomName = 12348
m_szLastPlaceName = 13744
m_thirdPersonViewAngles = 12760
m_totalHitsOnServer = 41880
m_vecOrigin = 312
m_vecVelocity = 276
m_vecViewOffset = 264
m_viewPunchAngle = 12320
